### ISSUE TITLE
How can I make it work with the bluetooth version?

### ISSUE THREAD

**Issue by amosbird** [bseibold/tpkbdctl#7]
`tpkbdctl -l` doesn't show the keyboard and `tpkbdctl -S 255` doesn't work.

**Comment by bseibold** [comment]
Neither the USB nor the Bluetooth version of the "Compact" keyboard are currently supported, just the original version (the one with the big palm rest).

**Comment by amosbird** [comment]
Yeah, lenovo sucks.
