### ISSUE TITLE
How can I further increase the speed of the trackpoint

### ISSUE THREAD

**Issue by amosbird** [bseibold/tpkbdctl#8]
I just set the sensitivity to 255. It still feels a bit slow. I also tried setting `libinput Accel Speed (311):     1.000000` which is not helpful. What can I do? thanks!

**Comment by bseibold** [comment]
There's nothing else you can set with this tool. Only other option I can think of is to increase mouse speed in general.

**Comment by amosbird** [comment]
@bseibold well, is it a limitation of HID interface? the serio2 builtin trackpoint has a `speed` endpoint under `/sys/device`.

**Comment by bseibold** [comment]
The linux driver and this tool are a result of analysing the USB HID Feature Reports the Windows driver sends when changing settings. Those feature reports consist of only four bytes of data, three of which I know the meaning of. See class `HidrawDevice` for details:

```python

def _write_settings(self):
    props = 0
    props |= 0x01 if self._press_to_select else 0x02
    props |= 0x04 if self._dragging else 0x08
    props |= 0x10 if self._release_to_select else 0x20
    props |= 0x80 if self._press_right else 0x40
    with open(self.hidraw_dev, 'w') as fd:
        ioctl(fd, 0xc0054806, pack('BBBBB', 4, props, 3, self._sensitivity, self._press_speed))
```

**Comment by amosbird** [comment]
ok, since the keyboard itself is the same as `x220 , t420 etc. `, can we mimic the linue trackpoint driver's behavior for writing `/sys/devices/platform/i8042/serio1/serio2/speed` ?

**Comment by bseibold** [comment]
I'm not sure what exactly you mean. Do you want to rename sensitivity to speed? Since this tool in a way mimics the Windows driver, I don't really want to change that. If you want to change the Linux driver, this is the wrong place to discuss.

**Comment by amosbird** [comment]
Um, I mean there are two endpoints `speed` and `sensitivity` in `/sys/devices/platform/i8042/serio1/serio2`

**Comment by bseibold** [comment]
Well, as I tried to explain above, this tool (and the driver) exposes all the settings I know about. If you find a speed setting, feel free to add it.
